### ISSUE TITLE
extreme mode and file descriptors

### ISSUE THREAD

**Issue by axyz** [mcollina/pino#100]
I'm probably missing something, but why is the file descriptor needed in extreme mode? From what I understood it is needed to flush data before exit, does it mean that the data of the last push will be stored on a file?

Anyway if I'm logging to a writable stream what should I initialize to `this.fd`? open a dummy file and get the descriptor? On the console seems to work also passing a random number (is there a way in node to safely get an unused fd other than the dummy file approach?). Is it the correct way to go or do I have to care about that file (or socket?) to retrieve the last push data in case of failures?

How is it handled when the stream is stdout?

Thanks for the help and for the great work here.

**Comment by mcollina** [comment]
> I'm probably missing something, but why is the file descriptor needed in extreme mode? From what I understood it is needed to flush data before exit, does it mean that the data of the last push will be stored on a file?

You can use extreme mode _only_ using a native (from core) stream, meaning a TCP/unix socket, a file, or stdout/sderr. Otherwise we cannot guarantee that a) if you process exit naturally, the log content will be on stdout/stderr b) you are not losing any log lines in case of a JS crash. 

> Anyway if I'm logging to a writable stream what should I initialize to this.fd? open a dummy file and get the descriptor? On the console seems to work also passing a random number (is there a way in node to safely get an unused fd other than the dummy file approach?). Is it the correct way to go or do I have to care about that file (or socket?) to retrieve the last push data in case of failures?

If you are logging to a writable stream, consider logging to a file, and then running a separate process to fetch and process that data. That is "the pino way", which will deliver high throughput.

We are still discussing those handlers, so feel free to join the discussion on https://github.com/mcollina/pino/issues/92.

Do you think we can improve the documentation? Would you like to send a PR?

**Comment by axyz** [comment]
Thanks for the info, will try to reword on the doc to see if it gets clearer.

Anyway can I use the dummy file approach to test the difference in performance? Or there will be no
improvement  if the data is processed in the same process?

moving the log handling on a separate process may be a risky refactor, but if the difference is notable I'd definitely would like to try it out as I will need to handle soon at least 10 times the current requests..

**Comment by mcollina** [comment]
The end result is about 10-20% faster in HTTP applications. It might be less, it really depends on your application, and what are the bottlenecks.

I would recommend you to benchmark both cases and check.

**Comment by mcollina** [comment]
> Anyway can I use the dummy file approach to test the difference in performance? Or there will be no
improvement if the data is processed in the same process?

Yes you can. The two things are not depending on each other (yet, maybe it will change in the future, who knows).
