### ISSUE TITLE
Sharing thoughts

### ISSUE THREAD

**Issue by btd** [mcollina/pino#23]
Hi, guys. I noticed you also write logger. I also spend some time one this [1](https://github.com/btd/rufus) and [2](https://github.com/btd/huzzah). Of course both much faster bunyan, intel and others. I did not compared to this project actually.

Right idea i got to improve speed - message compilation. So just compile string message to function producing simple string or json string - and you will gain huge speed improvement.

**Comment by davidmarkclements** [comment]
hey @btd we actually started creating functions from strings, in 294ea421 we moved away from that since `eval` / `new Function` tends to scare people away, and if no one's going to use it, what's the point. 

Even at that I recently attempted the same thing again (this time using `new Function`), just to see if we could squeeze any more performance out, and the results are negligible. Essentially, we're optimized to the point where we're on par to the building functions from strings approach, without having to scare people with eval.

Having said that, if you want to give your suggestion a go with pino it'd be awesome if you could prove me wrong (say if you can get another 20% that's worth creating a pino fork "pino-renegade" for people who don't mind their loggers using eval).

Closing for now, but let me know your plans, and thanks for sharing those other other loggers!
