### ISSUE TITLE
RingBuffer / extreme mode

### ISSUE THREAD

**Issue by gillesdemey** [mcollina/pino#41]
I was wondering if something like Bunyan's RingBuffer would be a useful addition to pino. 

It'd be useful to just buffer n-lines of logs in memory and being able to flush them manually, much like extreme mode but with manual control over the flush.

Perhaps we can expose an API on top of extreme mode?

https://github.com/trentm/node-bunyan#raw--ringbuffer-stream

**Comment by davidmarkclements** [comment]
this would be quite easy to do performantly for *bytes* (not lines) - we actually have all the parts

There is a `flush` method (we need to document that)

The amount of bytes is 4096 and is non-configurable but we could make that configurable (although our tests showed that 4096 yielded the highest speeds) 

Each record is atomic (e.g. it won't be spread across two flushed) so there's no concern there

Where the difficulty comes in, in terms of preserving performance is counting lines instead of bytes, and also the possibility of degrading perf by setting an unsuitable byte size

What use case do you have in mind for this - does it absolutely need to be flushed by rec count instead of byte count?

**Comment by mcollina** [comment]
I agree with the analysis of @davidmarkclements, and I propose:

1. make the amount of bytes configurable, this _might_ be application dependent, albeit 4KB is what we found be the sweet spot
2. document the `flush` method (it's already there), see #42 
3. to not count by line, because even if is doable, it will make achieving the "sweet" spot trickier, as it depends on the line length which is hard to predict

@gillesdemey would you like to send a PR? This is the `flush` method: https://github.com/mcollina/pino/blob/master/pino.js#L187-L194.

**Comment by gillesdemey** [comment]
> What use case do you have in mind for this - does it absolutely need to be flushed by rec count instead of byte count?

No, the byte count is good enough :)

We've built a simple sandbox execution environment to run untrusted code that returns the result and some logs when `console.log` or any other variant is invoked. But to prevent them from overflowing the process we needed to cap the logs somehow.

**Comment by mcollina** [comment]
So, is `flush` ok for you, do you need more, or it is just a documentation issue?

**Comment by gillesdemey** [comment]
From quickly glancing over the source it seems that the buffer is flushing automatically. 

ie. if I generated 8kb of logs they will have to be consumed by the stream and be written somewhere — even though I'd like to only keep 4kb around, so not just manually flushing it before the buffer is full.

I'm not sure how to achieve that with the current behaviour?
Perhaps an option that specifies that a `flush` will occur manually?

Or maybe my specific use-case is just too exotic in which case it wouldn't make sense to complicate the API :)

**Comment by mcollina** [comment]
I don't understand what you want to achieve :(.

**Comment by davidmarkclements** [comment]
is that you want to throw logs away once an upper limit is reached?

**Comment by gillesdemey** [comment]
Sorry for being somewhat unresponsive, been a busy weekend :)

> is that you want to throw logs away once an upper limit is reached?

Yes, but I realise now that that's probably not very useful if you're using buffers. 

When counting lines you can always pop the last one, when working with a buffer however you'll always have to throw it away entirely.

**Comment by davidmarkclements** [comment]
hmm okay - so it could be possible with a buffer if you keep track of each `\n` in the buffer, and then slice from that position to remove the oldest log. Bearing in mind that buffer is currently a string (rather than an actual buffer) that may not be the most performant way. 

I'm not sure whether @mcollina would agree but this is potentially a plugin

**Comment by mcollina** [comment]
I keep on missing the use case (sigh).

So you want to have a subsystem that can log as much as it wants, but just "cut" and print the latest X lines?
What if we add a switch to avoid auto-flushing?

The best way for achieving this is probably by using an object Transform stream and keep pino with extreme mode disabled. In the object Transform, you can maintain a "shifting buffer", and keep up to X in the queue. When the script ends, you can print all of those.

**Comment by davidmarkclements** [comment]
essentially it's this `node logging-process | tail -n $amountOfLines` - but with some guarantee of memory control

**Comment by davidmarkclements** [comment]
I agree with @mcollina passing in a transform stream that manages the memory is the best way to go here - which makes it outside pino. @gillesdemey let us know if you do this (or need any help) and we'll add it to readme as ringbuffer equivalent

**Comment by gillesdemey** [comment]
I agree that the transform stream makes the most sense and that the functionality doesn't belong in the library. 

I'll see if I can whip up a module that can be added to the README that acts as a RingBuffer

**Comment by gillesdemey** [comment]
I'm not sure wether or not this is useful to anyone else, but the following gist implements my use-case that allows me to buffer x lines of logs and retrieve them manually using a simple writable stream.

https://gist.github.com/gillesdemey/71d9d02108e469320deaa1251c5f2ecf

**Comment by davidmarkclements** [comment]
Sweet @gillesdemey - I've put some comments on the gist, let us know if you pub. as module
