### ISSUE TITLE
API for "transports"

### ISSUE THREAD

**Issue by matiasinsaurralde** [mcollina/pino#9]
Hi, I'm working on a project where Winston & custom "transports" are used.

I would be happy to replace Winston with pino, because it looks so much better :sunglasses: 

Do you have any API idea for supportings "transports" (I'll be happy to collaborate with some transports for Redis, AMQP, etc.)?

This is what Winston documentation says about transports:

https://github.com/winstonjs/winston/blob/master/docs/transports.md

**Comment by matiasinsaurralde** [comment]
Perhaps I should implement a ```Writable``` and see how it goes!

**Comment by mcollina** [comment]
There will never be an API for transports, or support for ObjectMode Writable streams. This library is fast because it does way less than the others. We are doing crazy things to make this fast (still no `eval`, @davidmarkclements removed that :P).

So, how do you do a transport? You create another node process to do that, and you pipe them together.

Something like:

```js
var split = require('split2')
var pump = require('pump')

pump(process.stdin, split2(JSON.parse), myAwesomeTransport)
```

Unix philosophy :).

Doing it inside the same process will add unnecessary load to your single-threaded node.js, effectively slowing you down.

I will put this in the README as well.

Anything to add @davidmarkclements?
